name: Ci for Staging

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build:

    runs-on: staging
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Copy jar file to another directory
        run: sudo cp /home/ubuntu/actions-runner-staging/_work/institution/institution/build/libs/institution-0.0.1-SNAPSHOT.jar /home/ubuntu/institution-staging

      - name: Finally Run the artifact service
        run: sudo systemctl restart institution-staging.service
